-- =========================
-- CATEGORIES (10개)
-- =========================
INSERT INTO categories (name, slug, description, created_at, updated_at) VALUES
('공지사항', 'notice', '중요한 공지사항을 확인하세요', NOW(), NOW()),
('자유게시판', 'free', '자유롭게 이야기를 나눠보세요', NOW(), NOW()),
('기술블로그', 'tech', '기술 관련 글을 공유합니다', NOW(), NOW()),
('개발일지', 'devlog', '개발 과정을 기록합니다', NOW(), NOW()),
('질문답변', 'qna', '궁금한 점을 질문하세요', NOW(), NOW()),
('프로젝트', 'project', '프로젝트를 소개합니다', NOW(), NOW()),
('스터디', 'study', '함께 공부해요', NOW(), NOW()),
('후기', 'review', '경험을 공유합니다', NOW(), NOW()),
('취업정보', 'career', '취업 관련 정보를 나눕니다', NOW(), NOW()),
('기타', 'etc', '기타 게시판', NOW(), NOW());

-- =========================
-- NORMAL USERS (40명 추가)
-- =========================
INSERT INTO users (email, password_hash, nickname, role, status, provider, provider_id) VALUES
-- 일반 사용자 1-20
('user1@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '개발자김철수', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user1'),
('user2@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '디자이너이영희', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user2'),
('user3@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '백엔드박민수', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user3'),
('user4@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '프론트최지은', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user4'),
('user5@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '풀스택정현우', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user5'),
('user6@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '데브옵스강민지', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user6'),
('user7@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'AI엔지니어송유진', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user7'),
('user8@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '데이터과학자임태호', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user8'),
('user9@blog.com',  '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '보안전문가윤서아', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user9'),
('user10@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'QA엔지니어한지훈', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user10'),
('user11@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '모바일개발자조은비', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user11'),
('user12@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '게임개발자류준혁', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user12'),
('user13@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '클라우드엔지니어홍수민', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user13'),
('user14@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '블록체인개발자노민석', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user14'),
('user15@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'IoT개발자서하은', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user15'),
('user16@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '임베디드개발자배성호', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user16'),
('user17@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '네트워크엔지니어오다연', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user17'),
('user18@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'DB관리자장우진', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user18'),
('user19@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '시스템엔지니어신예린', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user19'),
('user20@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '아키텍트고동현', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user20'),

-- 일반 사용자 21-40
('user21@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '주니어개발자권나영', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user21'),
('user22@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '시니어개발자문재현', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user22'),
('user23@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '인턴개발자안소희', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user23'),
('user24@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '리드개발자진승우', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user24'),
('user25@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '테크리드황아름', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user25'),
('user26@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'CTO후보남궁민', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user26'),
('user27@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '스타트업개발자유채원', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user27'),
('user28@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '대기업개발자표성진', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user28'),
('user29@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '외주개발자허윤아', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user29'),
('user30@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '프리랜서손태양', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user30'),
('user31@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'AI연구원양지수', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user31'),
('user32@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '머신러닝엔지니어최도윤', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user32'),
('user33@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '빅데이터분석가구하린', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user33'),
('user34@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'DBA전문가소현수', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user34'),
('user35@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '인프라엔지니어문지아', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user35'),
('user36@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', 'SRE엔지니어변우빈', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user36'),
('user37@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '플랫폼개발자나서연', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user37'),
('user38@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '솔루션개발자도준영', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user38'),
('user39@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '기획자출신개발자강예은', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user39'),
('user40@blog.com', '$2a$10$EixZaYVK1fsbw1ZfbX3OXePaWxn96p36Ew5z9z6pG9v7K4l1kK9iK', '디자이너출신개발자마도현', 'ROLE_USER', 'ACTIVE', 'LOCAL', 'user40');

-- =========================
-- POSTS (100개)
-- =========================
INSERT INTO posts (title, content, author_id, category_id, view_count, status, created_at, updated_at) VALUES
-- 공지사항 (5개)
('[공지] 블로그 서비스 오픈 안내', '안녕하세요. 블로그 서비스가 정식 오픈되었습니다. 많은 관심과 이용 부탁드립니다.', 1, 1, 523, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
('[공지] 이용약관 변경 안내', '2025년 1월 1일부터 이용약관이 변경됩니다. 자세한 내용은 본문을 확인해주세요.', 2, 1, 412, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
('[공지] 개인정보 처리방침 업데이트', '개인정보 처리방침이 업데이트되었습니다. 변경사항을 확인해주세요.', 1, 1, 389, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
('[공지] 서버 점검 안내 (1/15)', '시스템 안정화를 위한 서버 점검이 예정되어 있습니다. 점검 시간: 2025-01-15 02:00~04:00', 3, 1, 156, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
('[공지] 새로운 기능 추가 안내', '좋아요 및 댓글 알림 기능이 추가되었습니다. 많은 이용 바랍니다.', 2, 1, 234, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),

-- 자유게시판 (15개)
('오늘 커피 한 잔 하실분?', '근처 카페에서 개발 이야기 나누면서 커피 한 잔 어떠세요?', 11, 2, 45, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
('주말에 뭐하고 계신가요?', '다들 주말에 어떻게 보내시나요? 저는 사이드 프로젝트 진행 중입니다.', 12, 2, 78, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
('최근에 읽은 기술 서적 추천', '클린 코드 다시 읽고 있는데 정말 좋네요. 추천합니다!', 13, 2, 123, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
('개발자 건강 관리 어떻게 하시나요?', '오래 앉아있다 보니 허리가 아파서... 다들 운동은 어떻게 하시나요?', 14, 2, 89, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
('재택근무 vs 출근 뭐가 좋을까요?', '재택근무 경험담 공유해주세요!', 15, 2, 156, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
('개발자 유튜브 채널 추천 부탁드려요', '공부하면서 보기 좋은 유튜브 채널 있으면 공유해주세요.', 16, 2, 201, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('첫 회사 선택 고민입니다', '스타트업과 대기업 중 어디가 좋을까요? 조언 부탁드립니다.', 23, 2, 178, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
('점심 메뉴 추천 받습니다', '회사 근처 맛집 아시는 분 계신가요?', 17, 2, 34, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
('개발자 모임 만들고 싶어요', '정기적으로 모여서 스터디하는 모임 만들면 참여하실 분?', 18, 2, 92, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('코딩 테스트 어떻게 준비하셨나요?', '이직 준비 중인데 코테가 너무 어렵네요...', 19, 2, 145, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
('사이드 프로젝트 같이 하실 분', 'AI 챗봇 만들어보려고 하는데 함께 하실 분 구합니다!', 20, 2, 167, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
('개발 공부 방법 공유', '저는 이렇게 공부했어요! 여러분의 방법도 궁금합니다.', 21, 2, 234, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
('개발자 장비 추천해주세요', '노트북 바꾸려고 하는데 추천 부탁드립니다. 예산은 200만원입니다.', 22, 2, 189, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
('회사에서 겪은 재미있는 일', '오늘 배포하다가 있었던 에피소드 공유합니다 ㅋㅋ', 24, 2, 312, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
('개발자 영어 공부 어떻게 하세요?', '기술 문서 읽을 때마다 영어가 어렵네요. 다들 어떻게 공부하시나요?', 25, 2, 276, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),

-- 기술블로그 (25개)
('Spring Boot 3.x 주요 변경사항 정리', 'Spring Boot 3.0부터 달라진 점들을 정리해봤습니다. Java 17 필수, GraalVM 지원 등...', 11, 3, 445, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),
('React 19 새로운 기능 톺아보기', 'React 19에 추가된 새로운 기능들을 실습 예제와 함께 소개합니다.', 12, 3, 523, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
('Docker와 Kubernetes 실전 활용법', '실무에서 사용하는 Docker와 K8s 구축 방법을 상세히 설명합니다.', 13, 3, 678, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 17 DAY), DATE_SUB(NOW(), INTERVAL 17 DAY)),
('JWT 인증 구현하기 (Spring Security)', 'Spring Security와 JWT를 활용한 인증 시스템 구축 가이드입니다.', 14, 3, 891, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
('MySQL 성능 최적화 팁 10가지', '인덱스 설계부터 쿼리 튜닝까지, 실무에서 바로 적용 가능한 최적화 방법들입니다.', 15, 3, 756, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 19 DAY), DATE_SUB(NOW(), INTERVAL 19 DAY)),
('Redis 캐싱 전략과 실무 적용', 'Redis를 활용한 다양한 캐싱 전략과 실제 적용 사례를 공유합니다.', 16, 3, 623, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
('마이크로서비스 아키텍처 구축 경험담', 'MSA 전환 프로젝트를 진행하면서 겪은 시행착오와 해결 방법들입니다.', 17, 3, 834, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 21 DAY), DATE_SUB(NOW(), INTERVAL 21 DAY)),
('TypeScript 고급 타입 활용법', '제네릭, 유틸리티 타입 등 고급 TypeScript 기능들을 실습 예제와 함께 설명합니다.', 18, 3, 567, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 22 DAY), DATE_SUB(NOW(), INTERVAL 22 DAY)),
('AWS Lambda로 서버리스 구축하기', 'AWS Lambda와 API Gateway를 활용한 서버리스 아키텍처 구축 가이드입니다.', 19, 3, 489, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 23 DAY), DATE_SUB(NOW(), INTERVAL 23 DAY)),
('GraphQL vs REST API 비교 분석', '두 가지 API 방식의 장단점을 비교하고 선택 기준을 제시합니다.', 20, 3, 712, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 24 DAY), DATE_SUB(NOW(), INTERVAL 24 DAY)),
('Next.js 14 App Router 완벽 가이드', 'App Router의 새로운 기능과 마이그레이션 방법을 설명합니다.', 21, 3, 645, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 25 DAY), DATE_SUB(NOW(), INTERVAL 25 DAY)),
('Git 고급 명령어와 전략', 'Rebase, Cherry-pick 등 실무에서 유용한 Git 명령어들을 소개합니다.', 22, 3, 534, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 26 DAY), DATE_SUB(NOW(), INTERVAL 26 DAY)),
('JPA N+1 문제 해결 방법', 'Fetch Join, EntityGraph 등을 활용한 N+1 문제 해결 방법을 설명합니다.', 23, 3, 923, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 27 DAY), DATE_SUB(NOW(), INTERVAL 27 DAY)),
('CI/CD 파이프라인 구축하기', 'Jenkins와 GitHub Actions를 활용한 자동화 배포 환경 구축 가이드입니다.', 24, 3, 778, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY)),
('Tailwind CSS 실무 활용 팁', '유틸리티 우선 CSS 프레임워크인 Tailwind의 실전 활용법을 공유합니다.', 25, 3, 456, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 29 DAY), DATE_SUB(NOW(), INTERVAL 29 DAY)),
('Python 비동기 프로그래밍 완벽 가이드', 'asyncio와 async/await를 활용한 비동기 프로그래밍 방법을 설명합니다.', 26, 3, 589, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
('모바일 앱 성능 최적화 기법', 'React Native와 Flutter 앱의 성능을 개선하는 다양한 방법들을 소개합니다.', 27, 3, 467, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 31 DAY), DATE_SUB(NOW(), INTERVAL 31 DAY)),
('보안 취약점 점검 체크리스트', 'OWASP Top 10 기반의 보안 점검 항목과 대응 방법을 정리했습니다.', 28, 3, 834, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 32 DAY), DATE_SUB(NOW(), INTERVAL 32 DAY)),
('Elasticsearch 검색 엔진 구축', 'ELK 스택을 활용한 로그 분석 및 검색 시스템 구축 방법입니다.', 29, 3, 612, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 33 DAY), DATE_SUB(NOW(), INTERVAL 33 DAY)),
('WebSocket으로 실시간 채팅 구현', 'Socket.io를 활용한 실시간 채팅 애플리케이션 구축 튜토리얼입니다.', 30, 3, 723, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 34 DAY), DATE_SUB(NOW(), INTERVAL 34 DAY)),
('테스트 주도 개발(TDD) 실전 가이드', 'Jest와 JUnit을 활용한 TDD 실습 예제와 Best Practice를 공유합니다.', 31, 3, 856, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 35 DAY), DATE_SUB(NOW(), INTERVAL 35 DAY)),
('Nginx 리버스 프록시 설정하기', 'Nginx를 활용한 로드 밸런싱과 SSL 인증서 적용 방법입니다.', 32, 3, 534, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 36 DAY), DATE_SUB(NOW(), INTERVAL 36 DAY)),
('MongoDB vs PostgreSQL 선택 가이드', 'NoSQL과 RDBMS의 차이점과 프로젝트에 맞는 DB 선택 방법을 설명합니다.', 33, 3, 678, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 37 DAY), DATE_SUB(NOW(), INTERVAL 37 DAY)),
('클린 아키텍처 적용 사례', '헥사고날 아키텍처를 실제 프로젝트에 적용한 경험을 공유합니다.', 34, 3, 945, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 38 DAY), DATE_SUB(NOW(), INTERVAL 38 DAY)),
('Vue 3 Composition API 마스터하기', 'Composition API의 핵심 개념과 실전 활용 방법을 정리했습니다.', 35, 3, 512, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 39 DAY), DATE_SUB(NOW(), INTERVAL 39 DAY)),

-- 개발일지 (20개)
('[개발일지] 블로그 프로젝트 시작', 'Spring Boot와 React로 블로그를 만들기 시작했습니다. 첫 날 개발 일지입니다.', 11, 4, 234, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 40 DAY), DATE_SUB(NOW(), INTERVAL 40 DAY)),
('[개발일지] JWT 인증 구현 완료', '오늘은 JWT 인증 시스템을 구현했습니다. Spring Security 설정이 복잡하네요.', 11, 4, 189, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 38 DAY), DATE_SUB(NOW(), INTERVAL 38 DAY)),
('[개발일지] Firebase 연동 성공', 'Google과 Kakao 소셜 로그인을 Firebase로 구현했습니다.', 11, 4, 156, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 36 DAY), DATE_SUB(NOW(), INTERVAL 36 DAY)),
('[개발일지] 게시글 CRUD 완성', '게시글 작성, 조회, 수정, 삭제 기능을 모두 구현했습니다.', 11, 4, 178, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 34 DAY), DATE_SUB(NOW(), INTERVAL 34 DAY)),
('[개발일지] 댓글 기능 추가', '게시글에 댓글을 달 수 있는 기능을 추가했습니다. 대댓글은 다음에...', 11, 4, 145, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 32 DAY), DATE_SUB(NOW(), INTERVAL 32 DAY)),
('[개발일지] 좋아요 기능 구현', '좋아요 토글 기능을 구현했습니다. 중복 방지를 위해 unique constraint를 추가했어요.', 11, 4, 167, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 30 DAY), DATE_SUB(NOW(), INTERVAL 30 DAY)),
('[개발일지] 관리자 페이지 작업', '사용자 관리와 통계 기능을 추가했습니다. 관리자의 권한이 막강하네요.', 11, 4, 123, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 28 DAY), DATE_SUB(NOW(), INTERVAL 28 DAY)),
('[개발일지] 프론트엔드 UI 개선', 'Tailwind CSS를 적용해서 디자인을 개선했습니다. 훨씬 깔끔해졌어요!', 12, 4, 201, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 26 DAY), DATE_SUB(NOW(), INTERVAL 26 DAY)),
('[개발일지] API 문서화 완료', 'Swagger로 API 문서를 자동 생성했습니다. 협업할 때 편할 것 같아요.', 12, 4, 134, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 24 DAY), DATE_SUB(NOW(), INTERVAL 24 DAY)),
('[개발일지] 배포 환경 구축', 'AWS EC2에 Docker로 배포했습니다. CI/CD 파이프라인도 구축했어요.', 13, 4, 245, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 22 DAY), DATE_SUB(NOW(), INTERVAL 22 DAY)),
('[개발일지] 성능 최적화 작업', '쿼리 튜닝과 캐싱을 적용해서 응답 속도를 50% 개선했습니다.', 13, 4, 289, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
('[개발일지] 버그 픽스 주간', '이번 주는 버그만 잡았네요. 테스트 코드의 중요성을 느꼈습니다.', 14, 4, 156, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
('[개발일지] 알림 기능 개발', '댓글과 좋아요 알림 기능을 추가했습니다. WebSocket을 사용했어요.', 14, 4, 198, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
('[개발일지] 검색 기능 고도화', 'Elasticsearch를 도입해서 검색 성능을 크게 개선했습니다.', 15, 4, 223, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
('[개발일지] 이미지 업로드 구현', 'AWS S3를 연동해서 이미지 업로드 기능을 추가했습니다.', 15, 4, 187, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
('[개발일지] 모바일 반응형 작업', '모바일 환경에서도 잘 보이도록 반응형 디자인을 적용했습니다.', 16, 4, 165, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
('[개발일지] 보안 강화 작업', 'XSS, CSRF 방어 로직을 추가하고 SQL Injection 취약점을 점검했습니다.', 16, 4, 234, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('[개발일지] 통합 테스트 작성', 'JUnit과 MockMvc로 API 테스트를 작성했습니다. 커버리지 80% 달성!', 17, 4, 178, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('[개발일지] 마크다운 에디터 추가', 'Toast UI Editor를 적용해서 마크다운으로 글을 작성할 수 있게 했습니다.', 17, 4, 201, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
('[개발일지] 프로젝트 회고', '3개월간의 개발을 마무리하며... 배운 점과 아쉬운 점을 정리합니다.', 11, 4, 345, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- 질문답변 (15개)
('[질문] Spring Boot 버전 선택', 'Spring Boot 3.x로 시작해도 될까요? 아니면 2.7을 사용하는 게 나을까요?', 21, 5, 89, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 15 DAY), DATE_SUB(NOW(), INTERVAL 15 DAY)),
('[질문] JWT 토큰 저장 위치', 'Access Token을 LocalStorage에 저장해도 안전한가요? 아니면 Cookie를 사용해야 하나요?', 22, 5, 145, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
('[질문] MySQL vs PostgreSQL', '새 프로젝트에서 어떤 DB를 사용하는 게 좋을까요? 차이점이 궁금합니다.', 23, 5, 178, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 13 DAY), DATE_SUB(NOW(), INTERVAL 13 DAY)),
('[질문] Docker 메모리 이슈', 'Docker 컨테이너가 메모리를 너무 많이 사용하는데 어떻게 해결하나요?', 24, 5, 123, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
('[질문] React 상태 관리 라이브러리', 'Redux, Zustand, Recoil 중 뭐가 좋을까요? 프로젝트는 중소 규모입니다.', 25, 5, 234, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 11 DAY), DATE_SUB(NOW(), INTERVAL 11 DAY)),
('[질문] API 버전 관리 방법', 'REST API의 버전을 어떻게 관리하시나요? URL에 포함? 헤더? 모범 사례가 궁금합니다.', 26, 5, 167, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
('[질문] Git 커밋 메시지 컨벤션', '커밋 메시지 작성 규칙이 있나요? Conventional Commits를 사용해야 할까요?', 27, 5, 189, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
('[질문] 에러 로깅 방법', '운영 환경에서 에러 로그를 어떻게 관리하시나요? Sentry? CloudWatch?', 28, 5, 201, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('[질문] 코드 리뷰 문화 정착', '팀에서 코드 리뷰 문화를 만들고 싶은데 어떻게 시작하면 좋을까요?', 29, 5, 156, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
('[질문] 개발 환경 분리', 'local, dev, staging, prod 환경을 어떻게 분리하고 관리하시나요?', 30, 5, 178, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('[질문] 페이지네이션 구현', '무한 스크롤 vs 페이지 번호, 어떤 방식이 더 나은가요?', 31, 5, 134, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
('[질문] 캐싱 전략', 'Redis 캐싱을 언제 사용하는 게 좋을까요? TTL은 어떻게 설정하나요?', 32, 5, 223, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
('[질문] 테스트 커버리지', '테스트 커버리지를 몇 퍼센트까지 맞추시나요? 100%가 필요한가요?', 33, 5, 145, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
('[질문] 배포 자동화', 'GitHub Actions와 Jenkins 중 뭐가 좋나요? 차이점이 궁금합니다.', 34, 5, 198, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
('[질문] 모니터링 도구', '서비스 모니터링은 어떤 도구를 사용하시나요? Grafana? Datadog?', 35, 5, 167, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),

-- 프로젝트 (10개)
('[프로젝트] AI 챗봇 서비스 출시', 'GPT API를 활용한 고객 상담 챗봇을 개발했습니다. 런칭 후기를 공유합니다.', 36, 6, 567, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 20 DAY), DATE_SUB(NOW(), INTERVAL 20 DAY)),
('[프로젝트] 쇼핑몰 리뉴얼 프로젝트', '레거시 시스템을 마이크로서비스로 전환한 경험을 공유합니다.', 37, 6, 489, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 18 DAY), DATE_SUB(NOW(), INTERVAL 18 DAY)),
('[프로젝트] 모바일 앱 개발기', 'React Native로 크로스 플랫폼 앱을 개발한 과정을 정리했습니다.', 38, 6, 423, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 16 DAY), DATE_SUB(NOW(), INTERVAL 16 DAY)),
('[프로젝트] 사내 도구 자동화', '반복 작업을 자동화하는 도구를 만들어 업무 효율을 2배 높였습니다.', 39, 6, 356, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 14 DAY), DATE_SUB(NOW(), INTERVAL 14 DAY)),
('[프로젝트] 실시간 대시보드 구축', 'WebSocket과 Chart.js로 실시간 데이터 시각화 대시보드를 만들었습니다.', 40, 6, 445, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 12 DAY), DATE_SUB(NOW(), INTERVAL 12 DAY)),
('[프로젝트] 블록체인 지갑 개발', 'Ethereum 기반의 암호화폐 지갑을 개발한 경험을 공유합니다.', 36, 6, 512, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
('[프로젝트] 영상 스트리밍 서비스', 'HLS 프로토콜을 활용한 동영상 스트리밍 플랫폼 구축기입니다.', 37, 6, 623, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('[프로젝트] IoT 디바이스 관리 시스템', 'AWS IoT Core를 활용한 스마트홈 관리 시스템을 개발했습니다.', 38, 6, 389, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('[프로젝트] 협업 도구 개발', 'Slack과 유사한 사내 메신저를 만든 과정을 공유합니다.', 39, 6, 478, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
('[프로젝트] 추천 시스템 구현', '머신러닝 기반의 상품 추천 알고리즘을 개발한 경험담입니다.', 40, 6, 534, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),

-- 스터디, 후기, 취업정보, 기타 (15개)
('[스터디] 알고리즘 스터디 모집', '매주 토요일 오후 2시, 백준 문제를 함께 풀어요!', 21, 7, 112, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 10 DAY), DATE_SUB(NOW(), INTERVAL 10 DAY)),
('[스터디] React 스터디 완료 후기', '3개월간 React를 공부한 스터디 후기를 남깁니다.', 22, 7, 89, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('[후기] 카카오 코딩테스트 후기', '2025 카카오 신입 코테 후기입니다. 문제 유형 공유해요.', 23, 8, 456, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
('[후기] 부트캠프 수료 후기', '6개월간의 부트캠프를 마치고... 솔직한 후기를 남깁니다.', 24, 8, 389, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('[취업] 이직 성공 팁 공유', '3년차 개발자의 이직 경험담을 공유합니다.', 25, 9, 567, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
('[취업] 기술 면접 질문 모음', '실제로 받았던 기술 면접 질문들을 정리했습니다.', 26, 9, 678, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY)),
('[스터디] Spring Boot 스터디원 모집', 'Spring Boot를 처음부터 차근차근 공부할 분 구합니다.', 27, 7, 134, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 3 DAY), DATE_SUB(NOW(), INTERVAL 3 DAY)),
('[후기] AWS 자격증 취득 후기', 'SAA-C03 합격 후기와 공부 방법을 공유합니다.', 28, 8, 345, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 2 DAY), DATE_SUB(NOW(), INTERVAL 2 DAY)),
('[취업] 포트폴리오 작성 가이드', '눈에 띄는 포트폴리오 만드는 방법을 알려드립니다.', 29, 9, 489, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 1 DAY), DATE_SUB(NOW(), INTERVAL 1 DAY)),
('[기타] 개발자 추천 도서 10선', '실력 향상에 도움이 됐던 책들을 소개합니다.', 30, 10, 234, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 9 DAY), DATE_SUB(NOW(), INTERVAL 9 DAY)),
('[기타] 개발자 유용한 툴 모음', '생산성을 높여주는 개발 도구들을 정리했습니다.', 31, 10, 312, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 8 DAY), DATE_SUB(NOW(), INTERVAL 8 DAY)),
('[기타] 개발 유튜버 추천', '구독하면 좋은 개발 유튜브 채널들을 소개합니다.', 32, 10, 278, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 7 DAY), DATE_SUB(NOW(), INTERVAL 7 DAY)),
('[기타] 개발자 컨퍼런스 후기', 'DEVIEW 2024 참석 후기를 공유합니다.', 33, 10, 201, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 6 DAY), DATE_SUB(NOW(), INTERVAL 6 DAY)),
('[기타] 개발 팟캐스트 추천', '출퇴근길에 듣기 좋은 개발 팟캐스트를 소개합니다.', 34, 10, 156, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 5 DAY), DATE_SUB(NOW(), INTERVAL 5 DAY)),
('[기타] 2025 개발 트렌드 전망', '올해 주목해야 할 기술 트렌드를 정리했습니다.', 35, 10, 445, 'PUBLISHED', DATE_SUB(NOW(), INTERVAL 4 DAY), DATE_SUB(NOW(), INTERVAL 4 DAY));
